# Config version. Do not change this
config-version = "2.7"

# Puerto público (Playit)
bind = "0.0.0.0:25565"

motd = "<#09add3>Mi Network No-Premium</#09add3>"
show-max-players = 100

# NO-PREMIUM
online-mode = false
force-key-authentication = false

prevent-client-proxy-connections = false

# Forwarding moderno (SÍ, incluso no-premium)
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

announce-forge = false
kick-existing-players = false

# Usar MOTD del Lobby
ping-passthrough = "description"

enable-player-address-logging = true

# ───────────────────────────────
# SERVIDORES BACKEND
# ───────────────────────────────
[servers]
lobby = "127.0.0.1:25566"
survival = "127.0.0.1:25567"

try = [
    "lobby"
]

# No necesario con Playit
[forced-hosts]

# ───────────────────────────────
# AVANZADO
# ───────────────────────────────
[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000

haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true

failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true
accepts-transfers = false

# ───────────────────────────────
# QUERY (NO NECESARIO)
# ───────────────────────────────
[query]
enabled = false
